services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: leaky-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - PORT=3000
    volumes:
      - ./server/public:/app/public
    networks:
      - leaky_default

networks:
  leaky_default:
    external: true
