-- AlterTable
ALTER TABLE "Account" ADD COLUMN     "balanceSyncDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "cashSyncDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
